FE: Redesign menu
kafbat/kafka-ui pull request #227
Opened 2024-03-19 02:38 UTC by Leshe4ka

Resolve #195 

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2024-03-27 11:22 UTC, Leshe4ka commented
review pls

2024-03-31 15:43 UTC, Mgrdich approved these changes

2024-03-31 15:43 UTC, Mgrdich commented on frontend/src/lib/hooks/useScreenSize.ts
> +    window.addEventListener('resize', checkScreenSize);
maybe we can write the function exactly in the `useEffect` so we don't have to lie about the dependencies for the `useEffect`.

2024-04-22 16:51 UTC, Haarolean requested changes
Quite broken with the light theme:
<img width="670" alt="image" src="https://github.com/kafbat/kafka-ui/assets/1494347/d051453f-072b-4386-9d06-b33bded7fa30">

2024-04-24 06:55 UTC, Leshe4ka commented
> Quite broken with the light theme: <img alt="image" width="670" src="https://private-user-images.githubusercontent.com/1494347/324544163-d051453f-072b-4386-9d06-b33bded7fa30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDA0MTksIm5iZiI6MTcxMzk0MDExOSwicGF0aCI6Ii8xNDk0MzQ3LzMyNDU0NDE2My1kMDUxNDUzZi0wNzJiLTQzODYtOWQwNi1iMzNiZGVkN2ZhMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDYyODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE5OWU3ZjZkMDZiYTIwYzRmOGUxNjA3NmQ3ZGY3OTExNjg0ODY2NWViNWM5MDMzOTJjZDUwMGE2ODJkNzM3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BYdJwxaehGAYvVZR-DRZP0Qpxf-SSfwstddWrlLb75o">

Resolved

2024-04-29 19:40 UTC, Haarolean approved these changes
Committed a fix for the status icon size, the rest seems to be good, thanks

2024-04-30 12:04 UTC, merged