Issue 372 - Icon color not updating with theme color
kafbat/kafka-ui pull request #452
Opened 2024-06-21 23:58 UTC by igloo12

Addresses Issue https://github.com/kafbat/kafka-ui/issues/372

![Screenshot 2024-06-21 at 4 55 36 PM](https://github.com/kafbat/kafka-ui/assets/2858207/a0ca9a31-f1e3-4560-9011-333343d3813e)
![Screenshot 2024-06-21 at 4 54 35 PM](https://github.com/kafbat/kafka-ui/assets/2858207/a112c975-573a-45d9-b008-fa1321bca995)

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Updated the icon svgs to use the theme
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

![Red-Panda-Image-for-Endangered-Excursion-scaled](https://github.com/kafbat/kafka-ui/assets/2858207/4bf497ca-a78c-4ab3-b411-24b28ffa0e12)

2024-06-22 08:48 UTC, Nilumilak reviewed
I think it would be better to connect global theme to the colors instead of making the svg transparent

2024-06-23 13:45 UTC, Nilumilak commented
> > I think it would be better to connect global theme to the colors instead of making the svg transparent
> 
> Isn't that what the `styled()` method does? I copied it from the edit icon. The `styled()` sets the fill color of the svg.

edit icon uses the global  theme for filling the svg
```tsx
fill={theme.icons.editIcon.normal}
```

2024-08-10 15:10 UTC, Haarolean requested changes

2024-08-10 15:10 UTC, Haarolean commented on frontend/src/components/common/Icons/CheckmarkIcon.tsx
> +      <path d="M25 48c-1.1 0-2.2-.4-3-1.2l-13-13c-1.6-1.6-1.6-4.2 0-5.8s4.2-1.6 5.8 0L25 38.8 49.2 14.6c1.6-1.6 4.2-1.6 5.8 0s1.6 4.2 0 5.8l-27 27c-.8.8-1.9 1.2-3 1.2z" />
What's happening here, why is the shape changed?

2024-08-10 15:10 UTC, Haarolean commented on frontend/src/components/common/Icons/CancelIcon.tsx
> -        stroke={theme.icons.cancelIcon}
the color should be different for two themes, how is this supposed to work after the changes you've introduced?

2024-10-16 00:52 UTC, closed without merging