BE: Cleanup in controller package
kafbat/kafka-ui pull request #504
Opened 2024-07-26 21:00 UTC by wernerdv

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
A little cleanup in the controller package.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2024-07-27 09:58 UTC, Haarolean requested changes
Regarding the openapi DTOs, I'd prefer to have builders rather than bulky constructors. As the built-in ones are deprecated for some reason, can I suggest adjusting openapi configuration adding [additionalModelTypeAnnotations](https://openapi-generator.tech/docs/generators/java/) with lombok builder annotations?

2024-07-27 22:26 UTC, wernerdv commented
@Haarolean Fixed

2024-08-05 08:30 UTC, Haarolean approved these changes

2024-08-07 19:31 UTC, merged

2024-08-07 19:31 UTC, Haarolean commented
@wernerdv thanks for your contribution!