Feature/issue#346
kafbat/kafka-ui pull request #509
Opened 2024-07-29 20:56 UTC by MDzaja

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Implementation of the feature described in #346.
Extends `io.kafbat.ui.serde.api.Serde.Serializer` to support message headers editing by custom serializers.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
A custom serializer was developed, and the feature was tested with it.
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
![maki (4)](https://github.com/user-attachments/assets/96041bc6-be61-48d5-8b86-516240f61cf4)

2024-12-18 16:03 UTC, Haarolean requested changes

2024-12-18 16:03 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/serdes/SerdeInstance.java
> +    return (Serde.Serializer) Proxy.newProxyInstance(
why we'd need a proxy here?

2025-01-05 10:46 UTC, MDzaja commented on api/src/main/java/io/kafbat/ui/serdes/SerdeInstance.java
> +    return (Serde.Serializer) Proxy.newProxyInstance(
We need a proxy here because the `Serializer` interface now has multiple methods, so we cannot use a simple lambda for wrapping (as was done previously). A proxy provides a **generic**, **scalable**, and **clean solution** to wrap all methods of the `Serializer` interface dynamically. This ensures that every method invocation on the interface is consistently wrapped with the necessary logic (e.g., `wrapWithClassloader`).

While it’s possible to use an explicit or anonymous class implementation to achieve the same goal, using a proxy reduces boilerplate and makes the code easier to maintain in the long run. For comparison, here’s how an anonymous wrapper class could look:

``` java
public Serde.Serializer serializer(String topic, Serde.Target type) {
    return wrapWithClassloader(() -> {
        var serializer = serde.serializer(topic, type);
        return new Serde.Serializer() {
            @Override
            public byte[] serialize(String input) {
                return wrapWithClassloader(() -> serializer.serialize(input));
            }

            @Override
            public byte[] serialize(String input, Headers headers) {
                return wrapWithClassloader(() -> serializer.serialize(input, headers));
            }
        };
    });
}
```

While this approach works, it introduces repetitive boilerplate for every method, which becomes harder to manage as the interface evolves.

2025-04-17 15:11 UTC, marcosschroh commented
Is there any news of this? We are facing a similar problem. We want serialize the value according to some `headers` values.

2025-04-17 15:19 UTC, Haarolean commented
> Is there any news of this @MDzaja ? We are facing a similar problem. We want serialize the value according to some `headers` values.

we'll take a look, thanks for bumping

2025-05-13 07:52 UTC, marcosschroh commented
Hi, Is there anything that we can do to help you with this feature?

2025-07-23 09:13 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/serdes/SerdeInstance.java
> +    return (Serde.Serializer) Proxy.newProxyInstance(
We've replaced the proxy with an anonymous class call no avoid stacking spring aop + our proxy on each call

2025-07-24 12:00 UTC, merged

2025-07-24 12:01 UTC, Haarolean commented
@MDzaja Thanks for your first contribution to kafbat ui! Sorry it took this long

2025-08-05 13:49 UTC, marcosschroh commented
Are you going to release this feature in https://central.sonatype.com/artifact/io.kafbat.ui/serde-api?

2025-08-05 13:59 UTC, Haarolean commented
@marcosschroh #1243