BE: Set default message polling mode
kafbat/kafka-ui pull request #649
Opened 2024-11-06 15:22 UTC by wernerdv

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
According to `MessagesApi` the mode argument (Messages polling mode) is optional, so a null value is possible.
However, the `getTopicMessagesV2` method has a check for a non-null value for the mode argument.
The suggested solution is to set the default value to EARLIEST if mode is null.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2024-11-06 17:05 UTC, wernerdv commented
@Haarolean Hello, PTAL.

2024-11-07 12:49 UTC, Haarolean requested changes

2024-11-07 16:42 UTC, wernerdv commented on api/src/main/java/io/kafbat/ui/controller/MessagesController.java
> +      var pollingMode = mode == null ? PollingModeDTO.EARLIEST : mode;
Done

2024-11-11 14:09 UTC, germanosin approved these changes

2024-11-17 10:09 UTC, merged

2024-11-17 10:09 UTC, Haarolean commented
@wernerdv thanks!