Issues/300 regex for rbac
kafbat/kafka-ui pull request #663
Opened 2024-11-19 10:36 UTC by francoisvandenplas

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Rbac now handle regex in values

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2025-01-14 09:08 UTC, callaertanthony commented
Hey ! Any chance to see this PR merged ?

2025-01-14 09:50 UTC, Haarolean commented
> Hey ! Any chance to see this PR merged ?

sorry, we'll take a look this week

2025-02-12 10:19 UTC, Haarolean requested changes
Thanks for covering this with tests, that's really helpful!
Left a few minor inline comments

2025-02-12 10:19 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
> +            .anyMatch(s -> principal.getName() != null && principal.getName().matches(s.getValue())))
this can't be null, there should be a condition check in `DefaultOAuth2User`

2025-02-12 10:19 UTC, Haarolean commented on api/src/test/java/io/kafbat/ui/config/RegexBasedProviderAuthorityExtractorTest.java
> +}
can we add a few tests to check negative scenarios (like user doesn't get assigned roles he shouldn't have; nothing explodes with unexpected values)?

2025-02-12 12:24 UTC, francoisvandenplas commented on api/src/test/java/io/kafbat/ui/config/RegexBasedProviderAuthorityExtractorTest.java
> +}
I added some tests and assertions.
We should get _PatternSyntaxException_ if pattern has unexpected values.

2025-02-18 16:27 UTC, Haarolean requested changes

2025-02-18 16:27 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/service/rbac/extractor/OauthAuthorityExtractor.java
> +            .anyMatch(s -> principalName != null && principalName.matches(s.getValue())))
same here

2025-02-26 10:11 UTC, callaertanthony commented
hey @Haarolean , is it possible for you to give a look again ? many thanks

2025-02-26 15:21 UTC, Haarolean commented
@callaertanthony thank you! If you have time, could you update our docs as well? https://github.com/kafbat/ui-docs

2025-02-27 15:09 UTC, Haarolean commented
@callaertanthony hey, good point! We've discussed this: we believe a better approach would be introducing a new boolean param like `isRegex` (nullable & defaults to false for back compatibility), which will indicate whether we should treat the value as regex or a string literal. This will guarantee backward compatibility AND reduce confusion if multiple fields are used instead. What do you think?

2025-02-27 18:17 UTC, callaertanthony commented
thanks @Haarolean , @francoisvandenplas I created this pr with the change : https://github.com/francoisvandenplas/kafka-ui/pull/1

2025-02-28 02:13 UTC, Haarolean commented
> thanks @Haarolean , @francoisvandenplas I created this pr with the change : [francoisvandenplas#1](https://github.com/francoisvandenplas/kafka-ui/pull/1)

could you rebase this branch instead please?

2025-02-28 13:04 UTC, Haarolean requested changes

2025-02-28 15:06 UTC, francoisvandenplas commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
I replace with `@Data` as _Yaml.load()_ needs an empty constructor in RegexBasedProviderAuthorityExtractorTest

2025-02-28 15:26 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
@francoisvandenplas can we use jackson instead? it can work with parametrized constructors.

2025-03-03 09:22 UTC, francoisvandenplas commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
Yes, we could, but we have to provide a constructor with _@jsonCreator_ annotation as :
```
  @JsonCreator
  public Subject(
      @JsonProperty("provider") Provider provider,
      @JsonProperty("type") String type,
      @JsonProperty("value") String value,
      @JsonProperty("isRegex") boolean isRegex
  ) {
    this.provider = provider;
    this.type = type;
    this.value = value;
    this.isRegex = isRegex;
  } 
```

2025-03-04 15:32 UTC, francoisvandenplas commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
There is some test failures.
rbac classes are also mapped by config properties hence the` @Data` on those classes.
Any idea ?

2025-03-05 19:12 UTC, callaertanthony commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
hello @francoisvandenplas , sorry, I don't have enough time to go further, but rollback to getter annotation and specific setters works : https://github.com/francoisvandenplas/kafka-ui/pull/2

2025-03-06 00:21 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @Setter
`@Data` itself generates setters for non-final fields and a constructor. So rolling back to using only `@Data` and loading a test file with jackson rather than snakeyaml should help.

2025-03-14 16:34 UTC, Haarolean requested changes
just one minor thing and we're good to merge. @francoisvandenplas would you mind updating docs as well? 
https://github.com/kafbat/ui-docs

2025-03-20 11:20 UTC, germanosin approved these changes

2025-03-20 11:36 UTC, Haarolean commented on api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
> +  @JsonProperty("isRegex")
Ah, that seems invalid, as jackson will add an extra `is` prefix

2025-03-20 14:30 UTC, merged

2025-03-20 14:31 UTC, Haarolean commented
@francoisvandenplas @callaertanthony thanks for your contribution! We just need to update docs now