BE: Chore: use record classes
kafbat/kafka-ui pull request #703
Opened 2024-12-12 00:58 UTC by yeikel

**What changes did you make?** (Give an overview)

Refactors the code to take advantage of records 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] Unit checks

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

**A picture of a cute animal (not mandatory but encouraged)**

![istockphoto-479513144-612x612](https://github.com/user-attachments/assets/e1fb1c16-f9b3-49a9-b622-6d3287de3c7b)

2024-12-23 17:53 UTC, yeikel commented
@Haarolean What is blocking the merge of this change? 

Thanks in advance!

2024-12-24 18:28 UTC, Haarolean requested changes

2024-12-24 18:28 UTC, Haarolean commented on serde-api/src/main/java/io/kafbat/ui/serde/api/SchemaDescription.java
> +  public SchemaDescription {
do we need a default constructor here?..

2024-12-24 18:28 UTC, Haarolean commented on serde-api/src/main/java/io/kafbat/ui/serde/api/DeserializeResult.java
> +public record DeserializeResult(String result, io.kafbat.ui.serde.api.DeserializeResult.Type type,
`io.kafbat.ui.serde.api.DeserializeResult.Type` - can we import this?
`String result` - `@nullable` won't hurt I guess considering the comment we had on line 16

2024-12-24 18:28 UTC, Haarolean commented on serde-api/src/main/java/io/kafbat/ui/serde/api/DeserializeResult.java
> -    return Objects.hash(result, type, additionalProperties);
why?

2025-03-12 20:33 UTC, Haarolean commented
hmu once (and if) it's ready to review :)

2025-03-12 20:33 UTC, closed without merging